-- Product identities and image sources checked against the linked manufacturer
-- pages on 2026-09-23. No inferred prices or ingredient claims.
insert into public.products (name, brand, category, summary, data_source, data_notes, image_url, image_source) values
('Lash XTNDR Mascara', 'e.l.f. Cosmetics', 'mascara', 'A tubing mascara with a tapered brush for length and separation.', 'seed', 'Manufacturer: https://www.elfcosmetics.com/products/lash-xtndr-mascara', 'https://cdn.shopify.com/s/files/1/0661/2251/4520/files/81588_Open_B_0005_Product_Master_V4_R.png?v=1776967332', 'brand_site'),
('Brow Lift', 'e.l.f. Cosmetics', 'brow', 'Clear styling wax for brushed-up brows. Apply a small amount with a spoolie.', 'seed', 'Manufacturer: https://www.elfcosmetics.com/products/brow-lift', 'https://cdn.shopify.com/s/files/1/0661/2251/4520/files/82998_OpenA_R.png?v=1776967202', 'brand_site'),
('Glow Reviver Lip Oil', 'e.l.f. Cosmetics', 'lip', 'A sheer tinted lip oil with a glossy finish and a large cushion applicator.', 'seed', 'Manufacturer: https://www.elfcosmetics.com/products/glow-reviver-lip-oil', 'https://cdn.shopify.com/s/files/1/0661/2251/4520/files/82004_OpenA_V7_R_1005c717-0347-4eed-ba9f-3cefb6bd5bdf.png?v=1780264231', 'brand_site'),
('H2O Proof Eyeliner Pen', 'e.l.f. Cosmetics', 'eyeliner', 'A liquid eyeliner pen with a fine felt tip. The brand describes the formula as waterproof.', 'seed', 'Manufacturer: https://www.elfcosmetics.com/products/h2o-proof-eyeliner-pen', 'https://cdn.shopify.com/s/files/1/0661/2251/4520/files/81606_OpenA_V2_R.png?v=1776967244', 'brand_site'),
('Stay All Night Micro-Fine Setting Mist', 'e.l.f. Cosmetics', 'setting_product', 'A fine makeup-setting spray. Shake the bottle before misting over finished makeup.', 'seed', 'Manufacturer: https://www.elfcosmetics.com/products/stay-all-night-micro-fine-setting-mist', 'https://cdn.shopify.com/s/files/1/0661/2251/4520/files/82805_FCSPR_OpenA_C.jpg?v=1776967396', 'brand_site'),
('Halo Glow Contour Beauty Wand', 'e.l.f. Cosmetics', 'bronzer', 'Liquid contour with a cushion tip for placing and blending soft definition.', 'seed', 'Manufacturer: https://www.elfcosmetics.com/products/halo-glow-contour-beauty-wand', 'https://cdn.shopify.com/s/files/1/0661/2251/4520/files/84704_OpenA_R.png?v=1776967250', 'brand_site'),
('Fine as Fleck Glitter Eyeshadow', 'e.l.f. Cosmetics', 'eyeshadow', 'A single glitter eyeshadow for a wash of sparkle, worn alone or over another shadow.', 'seed', 'Manufacturer: https://www.elfcosmetics.com/products/fine-as-fleck-glitter-eyeshadow', 'https://cdn.shopify.com/s/files/1/0661/2251/4520/files/84890_OPEN-A_v4_R.png?v=1776967239', 'brand_site'),
('Halo Glow Highlight Beauty Wand', 'e.l.f. Cosmetics', 'highlighter', 'A liquid highlighter with a cushion-tip applicator for targeted glow.', 'seed', 'Manufacturer: https://www.elfcosmetics.com/products/halo-glow-highlight-beauty-wand', 'https://cdn.shopify.com/s/files/1/0661/2251/4520/files/84690_OpenA_R.png?v=1776967257', 'brand_site')
on conflict (name, brand) do nothing;
